### ISSUE TITLE
Maven definition

### ISSUE THREAD

**Issue by cburgmer** [codeniko/JsonPathKt#3]
Hey,

I'm not really good at either Kotlin or Maven, so I've tripped over
```
<dependency>
  <groupId>com.nfeld.jsonpathlite</groupId>
  <artifactId>json-path-lite</artifactId>
  <version>1.1.0</version>
  <type>pom</type>
</dependency>
```
If I remove `<type>pom</type>`, then Maven will happily compile, otherwise it will fail with
```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.3.40:compile (compile) on project query: Compilation failure
[ERROR] /Users/me/query/src/main/java/query/App.kt:[8,27] Unresolved reference: nfeld
```
Is there a reason for including it?

**Comment by codeniko** [comment]
Hi, I didn't test this since I personally use gradle in my projects. By removing `type`, I believe it defaults to `jar`. This may be a mistake on my part and it should actually be `jar`. To answer your question, there is no reason for including it. If it works without the type specified, that means the default value works. I'll also update the README. Thanks!

**Comment by codeniko** [comment]
Updated the readme
